emit:
  - "@typespec/json-schema"
  - "@agentschema/emitter"
options:
  "@typespec/json-schema":
    emitter-output-dir: "{cwd}/tsp-output/json-schema"
    emitAllModels: true
    emitAllRefs: true
    file-type: yaml
  "@agentschema/emitter":
    emitter-output-dir: "{cwd}/tsp-output"
    root-object: "AgentSchema.Core.AgentManifest"
    emit-targets:
      - type: markdown
        output-dir: "../docs"
      - type: CSharp
        output-dir: "../runtime/csharp/AgentSchema.Core/Model"
        test-dir: "../runtime/csharp/AgentSchema.Core.Tests/Model"
      - type: Python
        output-dir: "../runtime/python/agentschema/src/agentschema/core"
        test-dir: "../runtime/python/agentschema/tests/core"
      - type: BotDefinition
        output-dir: "../runtime/definition"
      - type: TypeScript
        output-dir: "./tsp-output/typescript"
